language: java

matrix:
  include:
    - jdk: openjdk9
      env: MVN_PROFILE=jdk9
    - jdk: openjdk10
      env: MVN_PROFILE=jdk10
    - jdk: openjdk11
      env: MVN_PROFILE=jdk11
script: "mvn test -P ${MVN_PROFILE}"
